name: anpr
description: "Project ANPR (Automatic Number Plate Recognition)"
version: 1.0.0+2

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  provider: 6.1.5+1
  camera: 0.11.3
  image: 4.6.0
  path_provider: 2.1.5
  google_mlkit_text_recognition: 0.15.0
  flutter_bloc: 9.1.1
  image_picker: 1.2.1
  tflite_flutter: 0.12.1
  crop_your_image: 2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/license_plate_detector_float16.tflite